# Generated by Django 3.1.2 on 2020-10-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='token',
            field=models.CharField(default='changeme', max_length=255, verbose_name='Token'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campus',
            name='thumbnail',
            field=models.ImageField(max_length=255, upload_to='', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(blank=True, choices=[('Sucesso', 'Sucesso'), ('Falha', 'Falha')], max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Quando ocorreu'),
        ),
    ]
