# Generated by Django 3.1.2 on 2020-10-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaportal', '0002_auto_20201009_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='status_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Status code'),
        ),
    ]
